import random
from collections import deque
from simulation.pid import PID

class CascadeControlSimulation:
    def __init__(self):
        # Configuration
        self.max_colorant_flow = 15.0  # L/min
        self.nominal_milk_flow = 50.0  # L/min
        self.valve_tau = 0.8           # Valve time constant (seconds)
        self.sensor_delay_sec = 2.0    # Transport delay (seconds)
        
        # PIDs
        # Outer Loop (Primary): Controls Color intensity by outputting target flow (0 to max_colorant_flow L/min)
        self.pid_outer = PID(kp=0.15, ki=0.03, kd=0.01, setpoint=100.0, output_limits=(0.0, 12.0))
        
        # Inner Loop (Secondary): Controls Flow by outputting valve % (0 to 100%)
        self.pid_inner = PID(kp=2.5, ki=1.5, kd=0.1, setpoint=0.0, output_limits=(0.0, 100.0))
        
        # State variables
        self.time = 0.0
        self.milk_flow = self.nominal_milk_flow
        self.valve_position = 0.0      # % (actual valve opening)
        self.valve_output = 0.0        # % (secondary controller output)
        self.colorant_flow = 0.0       # L/min (actual flow)
        self.colorant_flow_sp = 0.0    # L/min (setpoint generated by outer loop)
        
        # Target parameters
        self.target_color = 100.0      # Target TCS3200 sensor reading (0 - 255)
        
        # Delay queue for TCS3200 sensor
        self.delay_steps = int(self.sensor_delay_sec / 0.1)
        self.ratio_history = deque([0.0] * self.delay_steps, maxlen=self.delay_steps)
        
        # Process outputs
        self.sensor_color_reading = 0.0
        self.clogging_factor = 1.0       # Clogging factor (1.0 = normal, 0.4 = clogged)
        
        # Disturbances
        self.milk_disturbance_active = False
        self.pressure_disturbance_active = False  # Inner loop disturbance (sudden pressure drop)
        
        # Data logger for plotting
        self.history = {
            "time": [],
            "milk_flow": [],
            "colorant_flow": [],
            "colorant_flow_sp": [],
            "valve_position": [],
            "valve_output": [],
            "target_color": [],
            "sensor_color": [],
            "validation_ok": []
        }
        
    def reset(self):
        self.time = 0.0
        self.milk_flow = self.nominal_milk_flow
        self.valve_position = 0.0
        self.valve_output = 0.0
        self.colorant_flow = 0.0
        self.colorant_flow_sp = 0.0
        self.pid_outer.reset()
        self.pid_inner.reset()
        self.ratio_history = deque([0.0] * self.delay_steps, maxlen=self.delay_steps)
        self.sensor_color_reading = 0.0
        self.clogging_factor = 1.0
        self.milk_disturbance_active = False
        self.pressure_disturbance_active = False
        
        for key in self.history:
            self.history[key].clear()

    def set_pid_params(self, kp_out, ki_out, kd_out, kp_in, ki_in, kd_in):
        self.pid_outer.kp = kp_out
        self.pid_outer.ki = ki_out
        self.pid_outer.kd = kd_out
        self.pid_inner.kp = kp_in
        self.pid_inner.ki = ki_in
        self.pid_inner.kd = kd_in

    def step(self, dt=0.1, auto_mode=True, manual_valve_input=0.0):
        # 1. Milk flow (wild flow)
        base_milk = self.nominal_milk_flow
        if self.milk_disturbance_active:
            base_milk = 75.0 if (int(self.time / 10) % 2 == 0) else 35.0
        
        noise = random.uniform(-0.5, 0.5)
        self.milk_flow = max(10.0, base_milk + noise)
        
        # 2. Mixing & Sensor Transport Delay
        # Ratio at mixing point
        if self.milk_flow + self.colorant_flow > 0.1:
            mixing_ratio = self.colorant_flow / (self.milk_flow + self.colorant_flow)
        else:
            mixing_ratio = 0.0
            
        self.ratio_history.append(mixing_ratio)
        
        # Read ratio from TCS3200 sensor after transport delay
        delayed_ratio = self.ratio_history[0]
        
        # Map ratio to TCS3200 color intensity reading (0 - 255)
        self.sensor_color_reading = min(255.0, delayed_ratio * 1000.0)
        
        # 3. Outer Loop Control (Primary)
        if auto_mode:
            self.pid_outer.setpoint = self.target_color
            # Outer loop computes target colorant flow (Setpoint for inner loop)
            self.colorant_flow_sp = self.pid_outer.compute(self.sensor_color_reading, dt)
        else:
            # If in manual mode, setpoint is determined by target_color mapped directly
            # to flow (simplified manual estimation)
            self.colorant_flow_sp = (self.target_color / 1000.0) * self.milk_flow
            
        # 4. Inner Loop Control (Secondary)
        if auto_mode:
            self.pid_inner.setpoint = self.colorant_flow_sp
            self.valve_output = self.pid_inner.compute(self.colorant_flow, dt)
        else:
            self.valve_output = manual_valve_input
            
        # 5. Valve Actuator Dynamics (First-Order Lag)
        d_valv = (self.valve_output - self.valve_position) / self.valve_tau
        self.valve_position += d_valv * dt
        self.valve_position = max(0.0, min(100.0, self.valve_position))
        
        # 6. Pressure Disturbance (Inner Loop disturbance)
        # E.g. pressure drops, causing actual flow to be less than normal for a given valve opening
        flow_gain = self.max_colorant_flow * self.clogging_factor
        if self.pressure_disturbance_active:
            flow_gain *= 0.5  # drop flow capacity by 50% due to line pressure drop
            
        # 7. Process flow rate
        self.colorant_flow = (self.valve_position / 100.0) * flow_gain
        self.colorant_flow = max(0.0, self.colorant_flow + random.uniform(-0.05, 0.05))
        
        # 8. Validation Logic (±5% tolerance for Cascade)
        validation_ok = 1.0 if abs(self.sensor_color_reading - self.target_color) <= max(3.0, self.target_color * 0.05) else 0.0
        
        # Log data
        self.history["time"].append(self.time)
        self.history["milk_flow"].append(self.milk_flow)
        self.history["colorant_flow"].append(self.colorant_flow)
        self.history["colorant_flow_sp"].append(self.colorant_flow_sp)
        self.history["valve_position"].append(self.valve_position)
        self.history["valve_output"].append(self.valve_output)
        self.history["target_color"].append(self.target_color)
        self.history["sensor_color"].append(self.sensor_color_reading)
        self.history["validation_ok"].append(validation_ok)
        
        # Increment time
        self.time += dt
